### ISSUE TITLE
will this work on cloudant?

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/add-cors-to-couchdb#1]

**Comment by SinanGabel** [comment]
Hi!
I believe not. At Cloudant one does something like this instead:

curl https://username:password@user.cloudant.com/_api/v2/user/config/cors -X PUT -H 'Content-Type: application/json' -d '
{
    "enable_cors": true,
    "allow_credentials": true,
    "origins": [
         "https://users_site.com",
         "https://www.users_site.com"
     ]
}'

**Comment by nolanlawson** [comment]
Correct, Cloudant has a different CORS setup.
