### ISSUE TITLE
Simple steps how to use (Not an issue but a request)

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/add-cors-to-couchdb#14]
Hello People,

Probably obvious to you but I don't know how to use your solution:;-(

I open the command box on my PC
 I point to the folder where I extracted the add-cors-to-couchdb.zip
 I write: add-cors-to-couchdb http://delafini.iriscouch.com -u mario@delafini.com -p mario123

I think I miss some basics.

Can you be so kind and tell me how to use it?

Kind regards,
Mario

**Comment by calvinmetcalf** [comment]
You need [node.js](https://nodejs.org/) installed

**Comment by nickcolley** [comment]
Yeah I think we should update the instructions to include some node instructions that we take for granted, thanks @MarioVanDenEijnde for raising this

**Comment by nickcolley** [comment]
Hey Mario,

Have you executed `npm install -g add-cors-to-couchdb` ?

**Comment by MarioVanDenEijnde** [comment]
Hello Nick and Calvin,

Thanks but we used curl directly and with help of the PouchDb guys managed to enable CORS.
Besides: we haven't got node.js installed.
Yet.
Because it appears everyone is using node.js nowadays.

Thanks again.

Kind regards,
Mario
