### ISSUE TITLE
Avoid native promises to support node 0.10

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/add-cors-to-couchdb#17]
Saw this error in [a PouchDB travis job](https://travis-ci.org/pouchdb/pouchdb/jobs/117460661):

```
/home/travis/build/pouchdb/pouchdb/node_modules/add-cors-to-couchdb/node_modules/node-fetch/index.js:40
        throw new Error('native promise missing, set Fetch.Promise to your favorite 
              ^
Error: native promise missing, set Fetch.Promise to your favorite alternative
    at new Fetch (/home/travis/build/pouchdb/pouchdb/node_modules/add-cors-to-couchdb/node_modules/node-fetch/index.js:40:9)
    at Fetch (/home/travis/build/pouchdb/pouchdb/node_modules/add-cors-to-couchdb/node_modules/node-fetch/index.js:36:10)
    at addCors (/home/travis/build/pouchdb/pouchdb/node_modules/add-cors-to-couchdb/index.js:74:10)
    at Object.<anonymous> (/home/travis/build/pouchdb/pouchdb/node_modules/add-cors-to-couchdb/bin.js:27:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

So apparently the fix is to set `global.Promise` to use a promise shim (in our case, `lie`) before we use `node-fetch`.

**Comment by nolanlawson** [comment]
**First-timer instructions:**

1. In `index.js`, set `global.Promise` conditionally to use `lie` in the case where it's not already set. This will ensure that native promises are used in Node 0.12+ but a fallback is use in Node 0.10
2. In `.travis.yml`, add a Travis test to run in Node 0.10 to verify that the fix works. To do this, you'll need to set up a [Travis matrix](); there is a pretty good example in [the PouchDB .travis file](https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L143-L152) about how to do this. Testing in both Node stable and 0.10 is fine; no need to test everything in between. You can keep re-submitting a PR until the PR passes in Travis.

**Comment by nolanlawson** [comment]
Related issue: https://github.com/pouchdb/pouchdb/pull/4985#issuecomment-203375310

**Comment by akash-pal** [comment]
How to solve this issue? Could you provide the updated version?

**Comment by nolanlawson** [comment]
I created this issue intending for first-timers to solve it. It's fairly easy to solve - you just need to define a `global.Promise` in case it's not available.

**Comment by htrampe** [comment]
Hi! I can't follow how to solve this issue - can u help with a short how-to? THX!

**Comment by nolanlawson** [comment]
```js
if (!global.Promise) {
  global.Promise = require('lie')
}
```

**Comment by nolanlawson** [comment]
I think I'll just fix this; it's been half a year

**Comment by nolanlawson** [comment]
Hah, turns out the fetch library we're using doesn't support Node 0.10 so well. So unfortunately this fix isn't even possible. Looks like we only support Node 4 and above. :/

```
test #1 "./bin.js http://127.0.0.1:3000" failed:
	expected "success"
	got "{ [FetchError: request to http://127.0.0.1:3000/_config/cors/headers failed, reason: socket hang up]\n  name: 'FetchError',\n  message: 'request to http://127.0.0.1:3000/_config/cors/headers failed, reason: socket hang up',\n  type: 'system',\n  errno: 'ECONNRESET',\n  code: 'ECONNRESET' }"
test #2 "curl http://127.0.0.1:3000/_config/cors/credentials" failed:
	expected ""true""
	got ""false""
```
